language: node_js

before_install:
  - tar xvzf yasm-1.3.0.tar.gz && cd yasm *
  - ./configure
  - make
  - sudo make install

before_script:
  - "echo 1 | ./chinachu installer"

notifications:
  email: false
